### ISSUE TITLE
Kursabschluss Subventionierungsarten erweitern

### ISSUE THREAD

**Issue by RolandStuder** [hitobito/hitobito_insieme#1]
Interesse Cerebral

### Subventionierung

Beim Kurs im Bereich Kursrapport z. B. (http://insieme.puzzle.ch/de/groups/1/events/3789/course_record) neue Felder:

* `Subventioniert` (bisher) wird zu `Subventioniert BSV`
* Neu: `Subventioniert Kanton`
* `anderes` (mit zusätzlichem Textfeld für näherer Beschreibung)

-> letztere zwei sollen keinen Einfluss aufs Reporting haben, sie werden wie nicht subventionierte Kurse behandelt (allenfalls könnte das später erweitert werden.)

![image](https://cloud.githubusercontent.com/assets/194364/21141683/d8c0d012-c13e-11e6-99fc-278eda05dc2d.png)

### Offene Fragen:

* Muss das noch an anderen Orten beachtet werden?

**Comment by codez** [comment]
An verschiedenen Orten werden nur subventionierte Kurse herangezogen. Sollen dort weiterhin nur durch BSV subventionierte Kurse beachtet werden, oder auch durch Kanton subventionierte? Dies würde entsprechend weitere Anpassungen mit sich ziehen.
