### ISSUE TITLE
EVENTS: Darstellungsfehler bei Blockkursen

### ISSUE THREAD

**Issue by mlue00** [hitobito/hitobito_insieme#132]
**Aktuelles Verhalten**
Wenn Blockkurse im Kursmenu erfasst werden, wird der vorgeschlagene Wert "gemäss TN-
Liste" mit einem Darstellungsfehler dargestellt.
Der Fehler tritt im Tab "Kursabschluss" unter "Ertrag" auf.

**Gewünschtes Verhalten**
Der Darstellungsfehler wird behoben.

**Schritte zu reproduzieren**
https://desk.insieme.ch/de/groups/316/events/4056/course_record

**Hitobito Version**
1.27.19.1

**Screenshot**
![image](https://user-images.githubusercontent.com/69250571/204149049-e8d39ba5-f9a3-4515-b0c7-4c1159ebc59e.png)

**Comment by kronn** [comment]
LGTM, alle PRs dazu sind erledigt.
