### ISSUE TITLE
Techstack update

### ISSUE THREAD

**Issue by olibrian** [hitobito/hitobito_insieme#25]
Insieme auf den aktuellen Techstack bringen

Vorbereitet im branch `rails-5`

Offene Tasks:
- [x] ama: Pending changes pushen
- [x] prawn-table funktioniert noch nicht mit dem neuen Rails, ich meine es handelt sich um https://github.com/prawnpdf/prawn-table/issues/120, eventuell mit downgrade der library lösbar

**Comment by kronn** [comment]
die Integrationsumgebung ist auf Rails 6 und Ruby 2.5.5 aktualisiert.
