### ISSUE TITLE
Sortierung Gruppen linke Ansicht

### ISSUE THREAD

**Issue by olibrian** [hitobito/hitobito_insieme#26]
Die Sortierung der linken Menü Ansicht sollte von A-Z sein. Funktioniert unter gewissen Umständen nicht.

Beispiel aus der Integrationsumgebung:
![Screenshot from 2020-04-07 08-19-31](https://user-images.githubusercontent.com/9592347/78636403-90f47480-78a8-11ea-9596-e2be467d7203.png)

**Comment by kronn** [comment]
Die Sortierung ist durcheinander geraten, leider ist nicht klar weshalb. Ich werde diese manuell zurücksetzen müssen. Ich würde dies im Rahmen des nächsten Wartungsfensters erledigen.

**Comment by kronn** [comment]
Die Gruppen sind in Produktion und Integration neu sortiert.
