### ISSUE TITLE
Automatisierung der Berechnung "Umlage Gemeinkosten"

### ISSUE THREAD

**Issue by kronn** [hitobito/hitobito_insieme#30]
Es scheint eine potentielle Feedback-Loop zu geben, die eine komplette Automatisierung erschwert. Der Wert, der hier eingetragen werden soll, kann vorgeschlagen werden, geht aber wohl auch in die Berechnung des vorgeschlagenen Wertes ein. Aktuell wird die Berechnung in einem Background-Job gemacht, wenn ein Wert manuell gesetzt ist.

Link: https://insieme.puzzle.ch/de/groups/1/events/general_cost_allocation/2020/edit

Ansätze:
- [x] ~~Muss die "Umlage Gemeinkosten" bei der Berechnung ignoriert werden?~~
- [x] Vorausgefülltes Formular, dass nur noch bestätigt werden muss?

Timeboxed angehen: es wäre schön, wenn das automatisch einfach das richtige macht, aber es ist nicht absolut kritisch.

**Comment by olibrian** [comment]
Umsetzung: Werte als Vorschlag direkt ins Formular einfügen (Ansatz 2)

**Comment by kronn** [comment]
Umsetzung in https://github.com/hitobito/hitobito_insieme/commit/1117106657ca4f56353c73cb039f967b9ec6b7f1#diff-f6c837250e94eda05329f17d0c321823
