### ISSUE TITLE
Anpassung der Berechung des Kapitalsubstrat

### ISSUE THREAD

**Issue by kronn** [hitobito/hitobito_insieme#34]
An sich wie im angehängte XLSX ersichtlich. In Worten:

- Feld 1: Die Bezeichnung des ersten befüllbaren Feldes wird angepasst auf	«Organisationskapital inkl. freie Reserven und freie Fonds per 31.12.XXXX (wobei XXXX= Reporting-Jahr bedeutet)
- Feld 2: Ein zweites Feld wird hinzugefügt mit der Bezeichnung «zweckgebundene Fonds Art. 74 (inkl. Schwankungsfond) per 31.12.XXXX
- Es soll ein neues Feld Summe ihrer DB4 von 2015-2019 als einzelne Zahl im desk in der «Maske» «Kapitalsubstrat angezeigt werden (-> einmalige Übernahme aus bestehendem Datenbestand)
- Ein neues Feld mit der Bezeichnung aufgelaufene DB4 der Vertragsperiode 2020-2023 soll angezeigt werden. Darin sollen die DB4 ab 2020 aus der Kostenrechnung aufsummiert werden
  - Feld 3: Die beiden Felder zu den DB4 sollen summiert werden. Bezeichnung beim Feld: «Summe der DB4 von 2015 bis XXXX (XXXX=Reporting Jahr)
  - Neben dem Feld soll ein Text angezeigt werden: «bei Vereinen mit IVB von **weniger** als CHF 300'000 werden die aufgelaufenen DB4 seit 2015 mitberücksichtigt
- Feld 1 wird mit dem Schlüssel gewichtet
- Feld 2 wird nicht gewichtet
- Feld 1+Feld 2 werden addiert, Feld 3 wird addiert, wenn der IVB des Vereins < 300'000 ist (Zahl aus KR übernehmen)
- Der Freibetrag wird abgezogen (200'000)
- Es resultiert das geschlüsselte Kaptialsubstrat

[Kapitalsubstratsberechnung neu.xlsx](https://github.com/hitobito/hitobito_insieme/files/4443786/Kapitalsubstratsberechnung.neu.xlsx)

**Comment by olibrian** [comment]
Bitte noch kurz überprüfen ob die Summen korrekt sind. In der Integrationsumgebung war es etwas seltsam.

Printscreen:
![image](https://user-images.githubusercontent.com/9592347/87439081-a1776200-c5f0-11ea-9862-9eb227b92f59.png)

**Comment by kronn** [comment]
Es wurde versehentlich die Summe für 2015-2019 an beiden Stellen ausgegeben. Dies ist jetzt korrigiert.
