### ISSUE TITLE
Kostenrechnung

### ISSUE THREAD

**Issue by olibrian** [hitobito/hitobito_insieme#37]
Link: https://insieme.puzzle.ch/de/groups/1/cost_accounting?year=2020

Dokument Insieme:

(:arrow_right: Siehe «KR Sicht ab Reporting 2020_Bsp Solothurn» bzw. «KR Sicht ab Reporting 2020_ mit Formeln Bsp Solothurn»)
> Habe die Spenden-Zeilen umbenannt so dass es wie im Excel "KR Sicht ab Reporting" aussieht, das stand hier nicht explizit.

**Anpassungen vertikal**

* [x] Alle nicht mehr benötigten Zeilen ausblenden (nicht löschen) ~~:arrow_right: Problem?~~
* [x] Zeile «Abschreibungen» ausblenden (neu unter «Sachaufwand»)
> Abschreibungen habe ich nur ausgeblendet, unter Sachaufwand (übriger Sachaufwand) habe ich nichts angepasst. > passt so.
* [x] Neue Bezeichnungen Zeilen Aufwände und Erträge
* [x] Neue Bezeichnung «Unternehmenserfolg» :arrow_right: «Ertrag minus Aufwand»
* [x] Zeilen «Direkte Spenden nicht Art. 74», «Abgrenzungen» sowie DB 1-3 ausblenden
> Es existiert keine Zeile «Abgrenzungen», diese konnte ich somit nicht ausblenden. > Wohl ein Fehler in der Konzeption. Kunde klärt noch definitiv ab.
* [x] Umlagen Personal, Räumlichkeiten, Verwaltung, Total Umlagen werden ersetzt durch eine Zeile «Gemeinkosten»

**Anpassungen horizontal**

* [x] Spalte «Abgrenzung Dachorganisation» ausblenden
* [x] Spalte «Personal» ausblenden ~~:arrow_right: Problem?~~
* [x] Spalten, «Räumlichkeiten», «Geschäftsführung» und «Mittelbeschaffung» unter neuer Kostenstelle «Gemeinkosten» anordnen
* [ ] Bestehender Kostenträger «Treffpunkte»: Berücksichtigung der Angaben in Kurserfassung, Leistungskategorie «Treffpunkte» sowie «Umlage Gemeinkosten»
> Ich verstehe nicht genau, welche Zahlen hier in welche Zeile der Spalte "Treffpunkte" übernommen oder summiert werden sollen. > Umsetzung Analog zu Tageskurse (gemäss Telco 14.7.)
* [x] Neuer Kostenträger «Medien & Publikationen»
* [x] Reihenfolge Kostenträger anpassen

**Anpassungen Erfassungsmaske** (am Bsp. Raumaufwand :arrow_right: Siehe «neue Erfassungsmaske»)
> Im Excel "neue Erfassungsmaske" ist zusätzlich zu «Medien und Publikationen» auch noch ein bisher nicht vorhandenes Feld «Sozialberatung», ich nehme an damit ist das existierende Feld "Beratung" gemeint.
> Es ist anhand dem Excel "neue Erfassungsmaske" und der Beschreibung unklar, was mit dem Feld Geschäftsführung (intern "verwaltung" genannt) passieren soll. Ich habe dieses Feld bei den Kostenträgern stehen lassen und es dort in der neu berechneten Summe einbezogen.

* [x] Die Felder «Räumlichkeiten» und «Mittelbeschaffung sollen unter «Gemeinkosten» gruppiert und summiert werden
* [x] Bei den Kostenträgern soll ein neues Feld für «Medien und Publikationen» geschaffen werden
> Es ist unklar, bei welchen Reports das neue Feld "Medien und Publikationen" angezeigt werden soll. Habe es überall da hinzugefügt, wo auch das Feld "Beratung" vorhanden ist.
* [ ] Die Zahlen der Kostenträger Jahreskurse, Blockkurse, Tageskurse, Treffpunkte sollen aus der Erfassung «Kurse» und «Sammelkurse» übernommen und als Summe dargestellt werden
> Ich brauche hier mehr Informationen, da ich mich nicht mit BSV, Finanzen und dem Insieme-Kurswesen auskenne. Beim Kursabschluss sehe ich folgende Werte welche ich übernehmen könnte:
> "Honorare inkl. Sozialversicherung", "Unterkunft / Raumaufwand", "Übriges inkl. Verpflegung", "Direkter Aufwand Total", "Ertrag Beiträge TN", "Total direkte Kosten", "Gemeinkostenanteil", "Total Vollkosten"
> Welche der oben genannten Werte soll in welche der folgenden Reports übernommen werden? (natürlich z.B. über alle Jahreskurse und Jahres-Sammelkurse summiert wenn ich richtig verstehe)
> "Lohnaufwand", "Sozialversicherungsaufwand", "Übriger Personalaufwand", "Honorare", "Raumaufwand", "Übriger Sachaufwand", "Leistungen", "Beiträge IV", "Beiträge Bund/Kantone/Gemeinden", "Zweckgebundene Spenden (Art. 74)", "Nicht zweckgebundene Spenden (Art. 74)"

> Input kommt noch vom Kunde.
* [x] Die Kostenträger werden gruppiert und summiert
* [x] «Kontrolle» umfasst alle Felder
* [x] Allgemein Notizen bei Kostenstellen: Option für zeitlose Notizen
    * ~~Nachfrage, wenn «Speichern» («Übernehmen für alle Jahre?»)~~
    * ~~Haken setzen «Für alle Jahre»~~
    * ~~Graue Schrift mit Vorjahreseintrag, ev. mit Haken «Vorjahreseintrag übernehmen»?~~
    * [x] Lösungsvorschlag Puzzle: Ein Button welcher den Text vom Vorjahr übernimmt. :arrow_right: wurde bereits umgesetzt: https://github.com/hitobito/hitobito_insieme/pull/43
* [x] in der Erfassungsmaske sollten die Felder «Mittelbeschaffung» bei den Ertragswerten ausgeblendet werden
* [x] in der Erfassungsmaske sollten die Kommentare zu den Kontengruppen ausgeblendet werden
> Es ist unklar, ob mit "Kommentare zu den Kontengruppen" die Nummer hinter dem Feld "Ertrag FIBU" oder der Platzhalter im Notizen-Feld gemeint ist. Da beide im Excel "neue Erfassungsmaske" nicht vorhanden sind habe ich beide entfernt.

> Passt so wie es aktuell umgesetzt ist.

**Comment by carlobeltrame** [comment]
Zweite Runde:
#### Anpassungen an den Zeilen der Übersichtstabelle
* [ ] Bezeichnungen der Zeilen wieder auf die Bezeichnungen von 2019 zurücksetzen (i.e. Spezial-Übersetzungen für VP2020 löschen). Ausnahmen: "Ertrag minus Aufwand", "Gemeinkosten"
* [ ] Zeile «Ertrag minus Aufwand» (vormals «Unternehmenserfolg») bitte tauschen mit Zeile «Deckungsbeitrag 4» (also Erfolg über Deckungsbeitrag anzeigen)

#### Anpassungen an den Spalten der Übersichtstabelle
* [ ] Bestehender Kostenträger «Treffpunkte»: Berücksichtigung der Angaben in Kurserfassung, Leistungskategorie «Treffpunkte» sowie «Umlage Gemeinkosten». Dies ist bei Tageskursen, Jahreskursen und Blockkursen schon so, analog für Treffpunkte umsetzen
* [ ] "Beratung" in "Sozialberatung" umbenennen

#### Anpassungen an den einzelnen Erfassungsmasken
* [ ] Die Zahlen der Kostenträger Jahreskurse, Blockkurse, Tageskurse, Treffpunkte sollen aus der Erfassung «Kurse» und «Sammelkurse» übernommen und als Summe dargestellt werden. Hier geht es um die 3 Felder «Honorare», «Unterkunft/Raumaufwand» und «übriges inkl. Verpflegung» aus den Kursen/Sammelkursen. Diese werden bereits in der Kostenrechnung unter den entsprechenden Kostenträgern angezeigt. Genau diese Werte aus der Kostenrechnung sollen auch in den entsprechenden 3 Erfassungsmasken (Honorare / Raumaufwand/Sachaufwand) sichtbar sein, wie im Beispiel «Raumaufwand» (Excel-Sheet). 
* [ ] "Beratung" in "Sozialberatung" umbenennen
