### ISSUE TITLE
Controlling

### ISSUE THREAD

**Issue by olibrian** [hitobito/hitobito_insieme#38]
Link: https://insieme.puzzle.ch/de/groups/1/controlling?returning=true

* [ ] Allgemein (-> Siehe «Erfassungsdatei_Reportingdaten_Version_0.9», Tabellenblätter E & F)
    * [ ] KlientInnen Statistik -> neu pro Verein für Erfassungsmappe BSV
        * [ ] Kursstatistik: Nur ausgefüllte Kantone anzeigen für Handübertrag? Wie aufwändig?
        * [ ] Export pro Verein für Copy-Paste in Erfassungsmappe? Wie aufwändig?
    * [x] Kennzahlen pro Verein
        * [x] Aufteilung nach Kategorien entfernen
        * [x] Aufteilung nach Kursinhalt
        * [x] Neu: «Medien & Publikationen Stunden»
        * [x] LUFEB: Aufteilung gemäss Zeiterfassung
        * [x] Neu: «Grundlagenarbeit Kurse & Treffpunkte»
* [x] Zusammenzug Zeiterfassungen -> 3 Exporte
    * [x] Aufteilung gemäss Input Zeiterfassung
> Also wie bisher? Oder was ist Input Zeiterfassung?
* [x] Konsolidierte Kursstatistik (alle)
    * [x] Analog Kursstatistik pro Verein (konsolidierte Sicht)
    * [x] inkl. Treffpunkte

**Comment by kronn** [comment]
Erste Schritte sind im Branch https://github.com/hitobito/hitobito_insieme/tree/feature/38-controlling enthalten.
