### ISSUE TITLE
Pflichtfelder Neuerfassung Person

### ISSUE THREAD

**Issue by olibrian** [hitobito/hitobito_insieme#60]
Es kann aufgrund der Pflichtfelder keine neue Person erstellt werden. In der entsprechenden View (https://insieme.puzzle.ch/de/groups/1/roles/new) können die Pflichtfelder nicht ausgefüllt werden, was dann zu einem Fehler führt.

![insieme_Person erfassen](https://user-images.githubusercontent.com/9592347/88764662-a520f200-d175-11ea-80e1-3996ebcd149e.jpg)

**Lösungsvarianten:**
1) Falls technisch möglich bevorzugt: Auf dieser Stufe sind nur Name/Vorname Pflicht, die anderen Felder müssen erst beim zweiten Schritt zwingend ausgefüllt werden.

oder

2) Ansonsten: Die anderen Pflichtfelder müssen/können auch bereits hier ausgefüllt werden.

**Comment by kronn** [comment]
Dies ist vergleichbar mit der externen Anmeldung. Hier wird auf der neuen Person `externally_registered = true` gesetzt, um die Validierungen der Adress- und Sprachfelder abzuschalten. Vielleicht ist es sinnvoll, das Attribute zu `newly_registered` umzubenennen, da es ja ein wiederkehrendes Konzept ist. Für die Externe Anmeldung existieren tests, trotzdem sollte man komplett über den Source `externally_registered` greppen, um das zu anzupassen.
