### ISSUE TITLE
Fehler beim Speichern neuer Kurse/Sammelkurse

### ISSUE THREAD

**Issue by kronn** [hitobito/hitobito_insieme#61]
Beim Erstellen von Kursen / Sammelkursen wird jeweils «Gruppen ist nicht gültig» angezeigt, Speichern ist nicht möglich

![Xk9quE](https://user-images.githubusercontent.com/72198/88806144-4dec4300-d1b0-11ea-9f4b-d61ec67f7904.jpg)

Lokal liess sich dies nicht nachstellen, auf der Integrationsumgebung passiert es jedoch.

**Comment by carlobeltrame** [comment]
Das Problem war, dass seit der [verbesserten E-Mail-Validierung](https://github.com/hitobito/hitobito/pull/981) die Haupt-E-Mail auf dem Dachverband insieme Schweiz als invalide markiert wurde, da sie eine @example.net E-Mail verwendete. Ich habe das behoben und zudem @example.net-Adressen auf den Integrationen pauschal zugelassen, ähnlich wie das schon mit @hitobito.example.com und @example.com gemacht ist. Kurse und Sammelkurse auf dem Dachverband kann man jetzt wieder erstellen. Auf Unterverbänden die gegebenenfalls noch @example.net-Adressen eingetragen haben funktionierts dann spätestens ab morgen.

**Comment by richardjubla** [comment]
Wir haben die gleiche Fehlermeldung beim anlegen eines Lager:

Fehler "Gruppen ist nicht gültig" 


![Image](https://github.com/user-attachments/assets/072b4938-111c-4764-b1ac-212fb625c3eb)

Da wir gültige Haupt-E-Mail auf dem "Dachverband" haben, wäre eine fehlende E-Mail Adresse oberhalb der Top-Knoten (Jubla/NEJB) möglich. (Zur Sicherheit ist hier nun eine angegeben)
