### ISSUE TITLE
Reporting: Zeiterfassung

### ISSUE THREAD

**Issue by kronn** [hitobito/hitobito_insieme#62]
### Basisinformationen

- [x]  CSV Export: «Total Kurse» umbenennen in «Total Kurse und Treffpunkte»
- [x] CSV Export: Neue Zeile «Faktor Kapitalsubstrat» (Division aus «Geschlüsseltes Kapitalsubstrat nach Art. 74 IVG» und «Limite Kapitalsubstrat»)
- [x] Ansicht: Neues Feld «Faktor Kapitalsubstrat» (Division aus «Geschlüsseltes Kapitalsubstrat nach Art. 74 IVG» und «Limite Kapitalsubstrat»)

### Angestellte / Ehrenamt mit Leistungsnachweis

- [x] Format Titel («Angestellte MitarbeiterInnen, gemäss Arbeitsvertrag» / «Leistungen zur Unterstützung und Förderung der Eingliederung Behinderter (LUFEB)» / «Medien & Publikationen» / etc.): Grösser, Fett
- [x] Kurse  «Kurse & Treffpunkte» umbenennen

### Ehrenamt ohne Leistungsnachweis: Felder gemäss neuem KSBOB anpassen

- [x] LUFEB: 2. «Förderung der Selbsthilfe / Unterstützung von Selbsthilfeorganisationen und -gruppen sowie Einzelpersonen»  «Förderung der Selbsthilfe» umbennennen
- [x] LUFEB:  «Eigene öffentlich zugängliche Medien und Publikationen» entfernen
- [x] Neu: «Medien & Publikationen» (verschieben aus LUFEB, analog zur Übersicht «Angestellte» bzw. «Ehrenamt mit Leistungsnachweis»)
- [x] Kurse  «Kurse & Treffpunkte» umbenennen

**Comment by olibrian** [comment]
Bitte noch kurz mit der Umsetzung warten.
