### ISSUE TITLE
Fehler in der Übersetzung

### ISSUE THREAD

**Issue by olibrian** [hitobito/hitobito_insieme#76]
Aus dem Mail von Sämi:

a) Dann noch ein anderes Anliegen: Ich habe die Übersetzungen von Deutsch auf Französisch gemacht. Bei der Übersicht der Kurse und Sammelkurse hält sich „Leistungskategorie“ aber hartnäckig (siehe Screenshot). Ich finde bei mir keinen entsprechenden Eintrag, der nicht oder falsch übersetzt ist und gehe deshalb davon aus, dass dieser Eintrag auf einer höheren Ebene ist, zu der ich keinen Zugriff habe. Könnt ihr das anpassen?

 

-          Übersicht Kurse: https://insieme.puzzle.ch/fr/groups/284/events/course?returning=true

-          Übersicht Sammelkurse: https://insieme.puzzle.ch/fr/groups/1/events/aggregate_course?returning=true

-          Der richtige Begriff auf Französisch ist „Catégorie de prestations“

b) Auf der Seite „Kapitalsubstrat werden zudem einige deutsche Begriffe angezeigt, obwohl ich die entsprechenden Begriffe im Transifex übersetzt habe - ausser der „Hinweis“-Satz, da fehlt mir noch der Text – alle anderen Begriffe müssten jetzt eigentlich Französisch sein. Kann dem jemand nachgehen?

![Kapitalsubstrat](https://user-images.githubusercontent.com/9592347/96419169-0a740480-11f4-11eb-9821-7a0a2bec47fc.jpg)

 
![Leistungskategorie](https://user-images.githubusercontent.com/9592347/96419172-0ba53180-11f4-11eb-9e61-2f17abe3099d.jpg)

**Comment by kronn** [comment]
ich habe die Übersetzungen manuell direkt angepasst und eben auf der Integrationsumgebung verifiziert. Für das Kapitalsubstrat waren Übersetzunen vorhanden und wurden bei mir lokal auch angezeigt. Warum diese nicht auf der Integrationsumgebung sichtbar waren, ist mir nicht klar. Die Übersetzung der Leistungskategorie in der Liste war tatsächlich "auf einer höheren Ebene", ich habe dies angepasst und auch gleich die existierende Übersetzung davon übernommen.
