### ISSUE TITLE
Rückmeldungen Insieme

### ISSUE THREAD

**Issue by olibrian** [hitobito/hitobito_insieme#77]
Findings 21.10.20 gemäss Dokument: Findings 21.10.20_obr

- [x] 28: Controlling: Zusammenzug Zeiterfassung
  - [x]  für Ehrenamt ohne Leistungsnachweise mit weniger Spalten
  - [x] für alle ohne "Total weitere personenspezifische Leistungen"
- [x] 27: Sammelkurse: Eingabefeld "Betreuungsstunden", Kurse: berechnetes Feld
- [x] 30: Übersicht Kostenrechnung: Korrektur der Umlagequote
- [x] 29: Umlage Gemeinkosten an korrigierte Berechnung anpassen
- [x] specs mit Beispiele aus Findings erstellen

**Comment by kronn** [comment]
Den letzten Punkt haben wir nach #78 ausgelagert.
