### ISSUE TITLE
2021.1 Bestehender Export «KlientInnen Statistik»

### ISSUE THREAD

**Issue by olibrian** [hitobito/hitobito_insieme#81]
Aus der Dokument von Insieme

Reihenfolge der Zeilen für alle Exporte `group_scope`: 
        ◦ Zuerst: insieme Schweiz
        ◦ Dann alle aufsteigend nach «BSV-Nummer»

Ziel: Befüllen der Tabs E / Kurse  und F / Treffpunkte
Anwenden für alle Vereine (Reihenfolge siehe oben) mit BSV Nummer

- [x] Neue Spalte C (zwischen «Kursinhalt» und «Total»)

- Titel: «Anzahl Kurse»
- Wert analog zu «Anzahl Kurse» in Kursexporten «Subventioniert alle»: https://insieme.puzzle.ch/de/groups/284/2028/aggregations

- [x] Neue Spalte D (zwischen «Anzahl Kurse» und «Nicht Beitragsberechtigte»)

- Titel: «Stunden»
- Werte:
   -  Bei Kursen: Analog zu «Effektive TeilnehmerInnentage» bzw. «Effektive TeilnehmerInnenstunden» in Kursexporten «Subventioniert alle»: https://insieme.puzzle.ch/de/groups/284/2028/aggregations
   -  Bei Treffpunkten: Summe aus «Anzahl Betreuungsstunden» in Kursexport «Subventioniert alle» PLUS «Grundlagenarbeit zu Kursen & Treffpunkten» anteilsmässig: ( WERT / VOLLKOSTEN{Jahreskurse+Blockkurse+Semesterkurse+Treffpunkte} ) x VOLLKOSTEN{Treffpunkte}
   - WERT ist  «Grundlagenarbeit zu Kursen & Treffpunkten»  aus der Zeiterfassung  «Angestellte» und «Ehrenamt mit Leistungsnachweis»)
   - (Summe + (( WERT / alle vollkosten) * TP-Vollkosten)

- [x] Neue Spalte E (zwischen «Anzahl Kurse» und «Total»)

- «Nicht Beitragsberechtigte»
- Wert analog zum Wert «davon nicht Bezugsberechtigte» in Kursexporten «Subventioniert alle»: https://insieme.puzzle.ch/de/groups/284/2028/aggregations

**Comment by olibrian** [comment]
Soll folgende Spalten:

Verein / Kurstyp | Kursinhalt | Anzahl Kurse| Stunden | Nicht Beitragsberechtigte | Total  | AG | AI | AR | BE | ...
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --

**Comment by olibrian** [comment]
2021.1 Bestehender Export «KlientInnen Statistik» |  
-- | --
Beispiel für Neue Spalte D |  
  | Beispiel
Summe aus «Anzahl Betreuungsstunden» in Kursexport «Subventioniert alle» | 3
«Grundlagenarbeit zu Kursen & Treffpunkten» anteilsmässig: WERT | 6
VOLLKOSTEN{Jahreskurse+Blockkurse+Semesterkurse+Treffpunkte} | 15
VOLLKOSTEN{Treffpunkte} (für «Angestellte» und «Ehrenamt mit Leistungsnachweis») | 7
  | 5.8

=B4+((B5/B6)*B7)

**Comment by kronn** [comment]
Übersetzung anpassen: kursdauer -> Leistungseinheiten

**Comment by kronn** [comment]
URL Export: https://insieme.puzzle.ch/de/groups/1/controlling?year=2021
URL Verein:  https://insieme.puzzle.ch/de/groups/278/events/course

Anpassungen:

- [x] Die Angabe der teilnehmenden Personen funktioniert einwandfrei.
- [ ] Die Anzahl Kurse funktioniert nur, wenn einzelne Kurse erfasst wurden. Ein Sammelkurs wird als 1 Kurs gezählt, auch wenn oben angegeben ist, dass es 5 Kurse sind. Hier müssten aber 5 Kurse gezählt werden. Im Export "Konsolidierte Kursstatistik" funktioniert das auch so, hier aber nicht.
- [ ] Die Leistungseinheiten stimmen noch gar nicht. Hier wird offensichtlich die Kursdauer übernommen, wir brauchen aber die Leistungseinheiten, also TN-Stunden, TN-Tage, Betreuungsstunden. 

Zahlenbeispiel (ohne Aufteilung nach Kanton)


Verein / Kurstyp | Kursinhalt | Anzahl Kurse | Leistungseinheiten | Nicht Beitragsberechtigte | Total
-- | -- | -- | -- | -- | --
SOLL (selbst berechnet) |   |   |   |   |  
Beta Test |   |   |   |   |  
Semester-/Jahreskurse | Weiterbildung | 1 | 160 | 10 | 15
Semester-/Jahreskurse | Sport/Freizeit |   |   |   |  
Blockkurse | Weiterbildung |   |   |   |  
Blockkurse | Sport/Freizeit | 3 | 45 | 3 | 50
Tageskurse | Weiterbildung |   |   |   |  
Tageskurse | Sport/Freizeit | 1 | 20 |   | 20
Treffpunkte | Treffpunkt | 5 | 75 |   | 20
  |   |   |   |   |  
IST (Export) |   |   |   |   |  
Beta Test | 1001 |   |   |   |  
Semester-/Jahreskurse | Weiterbildung | 1 | 10 | 1 | 15
Semester-/Jahreskurse | Sport/Freizeit |   |   |   |  
Blockkurse | Weiterbildung |   |   |   |  
Blockkurse | Sport/Freizeit | 1 | 15 | 3 | 50
Tageskurse | Weiterbildung |   |   |   |  
Tageskurse | Sport/Freizeit | 1 | 1 |   | 20
Treffpunkte | Treffpunkt | 1 | 50 |   | 20

**Comment by kronn** [comment]
URL Export: https://insieme.puzzle.ch/de/groups/1/controlling?year=2021
URL Verein: https://insieme.puzzle.ch/de/groups/278/events/course

Anpassungen:

- [x] Die Spalte "Leistungseinheiten" soll "LE Beitragsberechtigte" genannt werden, die Spalte "Nicht Beitragsberechtigte" soll "LE Nicht Beitragsberechtigte" genannt werden
- [ ] Bei Sammelkurse soll der manuell berechnet Wert "tage_weitere" verwendet werden.
- [ ] Das Feld "LE Beitragsberechtige" enthält aktuell alle Teilnehmer, soll aber "Alle (bisheriger Wert) - LE Nichtbeitragsberechtigte" sein. 
- [ ] Die Anteilsberechnung ist noch nicht korrekt:

Berechnung SOLL Leistungseinheiten Treffpunkt |  
-- | --
Grundlagenarbeit zu Kursen & Treffpunkten | 20
Total Aufwand Jahreskurse | 1495.24
Total Aufwand Blockkurse | 4990.48
Total Aufwand Tageskurse | 1497.62
Total Treffpunkte | 3244.05
Anteil aus GL-Arbeit Kurse/Treffpunkte | 5.77881413222485
Leistungseinheiten aus erfassten Treffpunkten | 75
SOLL-Wert | 80.7788141322249

**Comment by kronn** [comment]
Einen Fehler in der KlientInnenstatistik haben wir noch gefunden:
Es geht um die "LE Nicht Beitragsberechtigt" (Spalte E) bei den Treffpunkten.
Hier sollte KEIN Wert angegeben werden.

- Wenn Treffpunkte als "Kurse" erfasst werden, bleibt das Feld leer (Beispiel im Anhang bei "Beta Test")
- Wenn Treffpunkte als "Sammelkurse" erfasst werden, wird das Feld befüllt (Beispiel im Anhang bei "Alpha Test")

Alpha Test Sammelkurse: https://insieme.puzzle.ch/de/groups/240/events/aggregate_course?returning=true
KlientInnen Statistik: https://insieme.puzzle.ch/de/groups/1/controlling?year=2021
