### ISSUE TITLE
2021.2 Neuer Export «LUFEB pro Verein»

### ISSUE THREAD

**Issue by olibrian** [hitobito/hitobito_insieme#82]
Ziel: Befüllen von Tab G / LUFEB
Position: «Zusammenzug Zeiterfassungen»
Pro Verein drei Felder übereinander
- Allgemeine Medien- und Öffentlichkeitsarbeit
- Themenspez. Grundlagenarbeit / Projekte
-  Förderung der Selbsthilfe

Werte: Jeweils die Summe der Subtotale dieser drei Werte von «Angestellte» und «Ehrenamt mit Leistungsnachweis» in der Zeiterfassung: https://insieme.puzzle.ch/de/groups/284/time_record/2028/employee_time/edit und https://insieme.puzzle.ch/de/groups/284/time_record/2028/volunteer_with_verification_time/edit
-  Spezialfall «Themenspez. Grundlagenarbeit / Projekte»:
   -  Oben beschriebene Summe PLUS
   - «Grundlagearbeit zu LUFEB» («Angestellte» und «Ehrenamt mit Leistungsnachweis») PLUS
   - «Grundlagenarbeit zu Kursen & Treffpunkten» anteilsmässig: WERT / VOLLKOSTEN{Jahreskurse+Blockkurse+Semesterkurse+Treffpunkte} x VOLLKOSTEN{Jahreskurse+Blockkurse+Semesterkurse} (für «Angestellte» und «Ehrenamt mit Leistungsnachweis»)

**Comment by olibrian** [comment]
2021.2 Neuer Export «LUFEB pro Verein» |  
-- | --
  |  
Summe der Subtotale dieser drei Werte von «Angestellte» und «Ehrenamt mit Leistungsnachweis» | 5
«Grundlagearbeit zu LUFEB» («Angestellte» und «Ehrenamt mit Leistungsnachweis») | 6
«Grundlagenarbeit zu Kursen & Treffpunkten | 6
VOLLKOSTEN{Jahreskurse+Blockkurse+Semesterkurse+Treffpunkte} | 15
VOLLKOSTEN{Jahreskurse+Blockkurse+Semesterkurse} (für «Angestellte» und «Ehrenamt mit Leistungsnachweis») | 8
  | 14.2

=B3+B4+((B5/B6)*B7)

**Comment by kronn** [comment]
Die Berechnung ist sollte mit folgenden Zahlen übereinstimmen:


Berechnung SOLL Themenspez. Grundlagenarbeit |  
-- | --
Grundlagenarbeit zu Kursen & Treffpunkten | 20
Total Aufwand Jahreskurse | 1495.24
Total Aufwand Blockkurse | 4990.48
Total Aufwand Tageskurse | 1497.62
Total Treffpunkte | 3244.05
Anteil aus GL-Arbeit Kurse/Treffpunkte | 14.2211858677751
Grundlagenarbeit zu LUFEB | 10
Themenspez. Grundlagenarbeit | 30
SOLL-Wert | 54.2211858677752
