### ISSUE TITLE
2021.3 Neuer Export «Organisationsdaten pro Verein»

### ISSUE THREAD

**Issue by olibrian** [hitobito/hitobito_insieme#83]
Ziel: Befüllen von Tab I / Organisationsdaten
Position: «Allgemein»
Pro Verein vier Felder übereinander

- (1) FTE angestellte MA insgesamt
- (2) FTE angestellte MA Betrieb Art. 74 IVG
- (3) FTE freiwillig und ehrenamtlich Mitarbeitende insgesamt
- (4) FTE freiwillig und ehrenamtlich Mitarbeitende des Betriebes Art. 74 IVG

Werte: Gemäss https://insieme.puzzle.ch/de/groups/89/time_record/2020/base_information und Kostenrechnung
- (1) Angestellte MitarbeiterInnen. Zeiterfassung (in 100% Stellen) / Ganze Organisation PLUS Honorare; Ertrag FIBU (aus Kostenrechnung, erste Spalte) dividiert durch 130 / 1900 (Stunden pro Arbeitsjahr `reporting parameter BSV-Year`)
- (2) Angestellte MitarbeiterInnen. Zeiterfassung (in 100% Stellen) / Art. 74 betreffend PLUS Honorare; Aufwand/Total (aus Kostenrechnung letzte Spalte vor Kontrolle) dividiert durch 130 / 1900 (Stunden pro Arbeitsjahr `reporting parameter  BSV-Year`)
- (3) Ehrenamtliche Arbeit mit Leistungsnachweis (in 100% Stellen) / Ganze Organisation
- (4) Ehrenamtliche Arbeit mit Leistungsnachweis (in 100% Stellen) / Art. 74 betreffen

**Comment by kronn** [comment]
130 als Konstante in Vp2020-Domainklasse hinterlegen. Wert ändert sich vermutlich nicht (oft).

**Comment by kronn** [comment]
Die Felder 1 und 2 sollen statt "Angestellte MitarbeiterInnen. Zeiterfassung (in 100% Stellen) / Ganze Organisation" jetzt "Angestellte MitarbeiterInnen. Gemäss Arbeitsvertrag (in 100% Stellen) / Ganze Organisation" verwenden.

Das Feld 3 solll jetz die Summe aus "Ehrenamtliche Arbeit mit Leistungsnachweis (in 100% Stellen) / Ganze Organisation" und "Ehrenamtliche Arbeit ohne Leistungsnachweis (in 100% Stellen) / Ganze Organisation" sein.
