### ISSUE TITLE
Leistungseinheiten zu den Treffpunkten in der Tabelle "Kennzahlen pro Verein"

### ISSUE THREAD

**Issue by olibrian** [hitobito/hitobito_insieme#90]
Aus dem Mail von Sämi, 16.03.2021

> Der Fehler von damals taucht leider noch an einem zweiten Ort: Auch die Leistungseinheiten zu den Treffpunkten in der Tabelle "Kennzahlen pro Verein" stimmen nicht.
> 
> 
> Im Anhang die beiden Exporte mit farbigen Markierungen, hier die Herkunft der Daten:
> 
> 
> https://desk.insieme.ch/de/groups/35/2020/aggregations (Treffpunkte subventioniert)
> 
> https://desk.insieme.ch/de/groups/1/controlling?returning=true (Kennzahlen pro Verein)
> 
> 
> Der Wert in der Kursstatistik stimmt (hast Du im Zuge des Mailwechsels unten ja korrigiert), der Wert in den Kennzahlen pro Verein nicht.

Anhang im Mail

# Tech-Spec

-

**Comment by kronn** [comment]
Ich habe keinen Fehler gefunden und nochmal zur Klärung nachgefragt.

**Comment by kronn** [comment]
Die Zahlen stimmen, es sind aber nicht genau die Zahlen, die gebraucht werden. Sie klären das intern und melden sich erneut.

Ich schliesse dieses Issue daher vorerst.
